### ISSUE TITLE
Incorrect exceptions and timeouts with wait=True

### ISSUE THREAD

**Issue by fasaxc** [jplana/python-etcd#81]
I try to wait on a directory key with a timeout of, say 1s.  If no updates to the key occur then the call times out after ~4s (not 1s as expected) and the exception is "EtcdException: No more machines in the cluster
" rather than a dedicated Timeout exception.

```
>>> import etcd
>>> c = etcd.Client(read_timeout=10)
>>> c.read("/foobar",waitIndex=88,wait=True,recursive=True,timeout=1)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/etcd/client.py", line 344, in read
    self.key_endpoint + key, self._MGET, params=params, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/etcd/client.py", line 576, in api_execute
    self._base_uri = self._next_server()
  File "/usr/local/lib/python2.7/dist-packages/etcd/client.py", line 534, in _next_server
    raise etcd.EtcdException('No more machines in the cluster')
EtcdException: No more machines in the cluster
```

```
$ pip list | grep python-etcd
python-etcd (0.3.2)
$ pip list | grep urllib
urllib3 (1.10.2)
```

**Comment by MaciekPytel** [comment]
I have the same issue. I think it's quite a serious problem, as it makes a watch with specified timeout pretty much useless (and I'd think it's a common use-case).

Basically the problem is as follows: by default urrlib3 retries 3 times on timeout. So when we specify the timeout of x seconds, what really happens is:
1. 4 requests with the specified timeout are run. (total time: ~4x seconds)
2. Once they all timeout MaxRetryError is raised by urllib3.
3. This triggers retries on different servers
4. Finally the call fails with EtcdException('No more machines in the cluster'), after much longer than specified in timeout.

I believe the fix would be to disable urllib3 retry when timeout is specified. However, if we do that we run into a different problem: if a pariticular etcd host goes down we won't retry on different servers (as the error we get won't be MaxRetryError).
I think the right thing to do would be to catch ConnectionError in addition to MaxRetryError and apply the same try-other-servers logic. Unfortunately ConnectionError was only introduced in urllib3 1.8.0, while python-etcd requires a version >= 1.7.1. 

Would this be a good enough reason to bump the urllib3 version up? Alternatively I can write some more complex error handling that would basically have to catch all urllib3 errors, figure out what happen and re-raise if appropriate (it's a bit ugly, but I can't think of anything else that would work with all existing versions of urllib3 since 1.7.1).

Either way I'm happy to submit a pull request.

**Comment by lavagetto** [comment]
I think this is part of a larger issue, which is supporting correctly timeouts both client-side and server-side. I don't have that much time to spend on this at the moment, but I'll try to organize some work on properly supporting etcd 2.0.

@MarciekPytel any pull request is welcome.

**Comment by CyberDem0n** [comment]
>>> import etcd
>>> c = etcd.Client()
>>> c.read("/foobar", wait=True, timeout=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/etcd/client.py", line 482, in read
    return self._result_from_response(response)
  File "/usr/local/lib/python2.7/dist-packages/etcd/client.py", line 700, in _result_from_response
    'Unable to decode server response: %s' % e)
etcd.EtcdException: Unable to decode server response: HTTPConnectionPool(host='127.0.0.1', port=4001): Read timed out.

But documentation tells that urllib3.exceptions.TimeoutError should be thrown.

The reason why this happens is:
https://github.com/jplana/python-etcd/blob/master/src/etcd/client.py#L692
`response.data` property will throw the right exception on which would be catch later on https://github.com/jplana/python-etcd/blob/master/src/etcd/client.py#L698
